//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentacion.Properties.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        internal static string caption_Aviso {
            get {
                return ResourceManager.GetString("caption_Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string caption_Error {
            get {
                return ResourceManager.GetString("caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación exitosa.
        /// </summary>
        internal static string caption_Exito {
            get {
                return ResourceManager.GetString("caption_Exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obligatorio de solo letras..
        /// </summary>
        internal static string message_ContenidoAlfabeticoRequerido {
            get {
                return ResourceManager.GetString("message_ContenidoAlfabeticoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obligatorio de solo letras y números..
        /// </summary>
        internal static string message_ContenidoAlfanumericoRequerido {
            get {
                return ResourceManager.GetString("message_ContenidoAlfanumericoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo institucional inválido..
        /// </summary>
        internal static string message_ContenidoCorreoInstitucionalInvalido {
            get {
                return ResourceManager.GetString("message_ContenidoCorreoInstitucionalInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo personal inválido..
        /// </summary>
        internal static string message_ContenidoCorreoPersonalInvalido {
            get {
                return ResourceManager.GetString("message_ContenidoCorreoPersonalInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El académico que desea registrar ya se encuentra en el sistema..
        /// </summary>
        internal static string messageBoxText_AcademicoExistente {
            get {
                return ResourceManager.GetString("messageBoxText_AcademicoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Académico no seleccionado, Por favor seleccione alguno de la tabla e intentelo de nuevo..
        /// </summary>
        internal static string messageBoxText_AcademicoNoSeleccinado {
            get {
                return ResourceManager.GetString("messageBoxText_AcademicoNoSeleccinado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor verifique que haya académicos sin roles registrados y que tenga buena conexión. .
        /// </summary>
        internal static string messageBoxText_AcademicosNoEncontrados {
            get {
                return ResourceManager.GetString("messageBoxText_AcademicosNoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo: Correo electrónico institucional debe tener una longitud máxima de 30 caracteres..
        /// </summary>
        internal static string messageBoxText_CampoCorreoInstitucionalExcedeLimite {
            get {
                return ResourceManager.GetString("messageBoxText_CampoCorreoInstitucionalExcedeLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo: Correo electrónico personal debe tener una longitud máxima de 100 caracteres..
        /// </summary>
        internal static string messageBoxText_CampoCorreoPersonalExcedeLimite {
            get {
                return ResourceManager.GetString("messageBoxText_CampoCorreoPersonalExcedeLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo para a matricula debe tener una longitud máxima de 9 caracteres..
        /// </summary>
        internal static string messageBoxText_CampoMatriculaExcedeLimite {
            get {
                return ResourceManager.GetString("messageBoxText_CampoMatriculaExcedeLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos: Nombre, Apellido paterno y Apellido materno deben tener una longitud máxima de 50 caracteres..
        /// </summary>
        internal static string messageBoxText_CamposNombreYApellidosExcedenLimite {
            get {
                return ResourceManager.GetString("messageBoxText_CamposNombreYApellidosExcedenLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique que todos los campos estén seleccionados..
        /// </summary>
        internal static string messageBoxText_CamposNoSeleccionados {
            get {
                return ResourceManager.GetString("messageBoxText_CamposNoSeleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede dejar ningún campo vacío.Por favor, verifique que todos los campos estén llenos..
        /// </summary>
        internal static string messageBoxText_CamposVacios {
            get {
                return ResourceManager.GetString("messageBoxText_CamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de que desea cancelar la operación?.
        /// </summary>
        internal static string messageBoxText_CancelarOperacion {
            get {
                return ResourceManager.GetString("messageBoxText_CancelarOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de que desea cancelar la operación? Toda la información se borrará, incluidas las problemáticas..
        /// </summary>
        internal static string messageBoxText_CancelarOperacionReporte {
            get {
                return ResourceManager.GetString("messageBoxText_CancelarOperacionReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo conectar con la base de datos. Por favor, inténtelo más tarde....
        /// </summary>
        internal static string messageBoxText_Conexion {
            get {
                return ResourceManager.GetString("messageBoxText_Conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un problema de red. Por favor verifique su conexión..
        /// </summary>
        internal static string messageBoxText_ConexionInternet {
            get {
                return ResourceManager.GetString("messageBoxText_ConexionInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Deseas guardar la información?.
        /// </summary>
        internal static string messageBoxText_ConfirmacionCambios {
            get {
                return ResourceManager.GetString("messageBoxText_ConfirmacionCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos del estudiante modificado ya se encuentran registrados en el sistema..
        /// </summary>
        internal static string messageBoxText_EstudianteExistente {
            get {
                return ResourceManager.GetString("messageBoxText_EstudianteExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información se ha registrado correctamente..
        /// </summary>
        internal static string messageBoxText_Exito {
            get {
                return ResourceManager.GetString("messageBoxText_Exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo siento!!, fecha de tutoría ha terminado :&apos;(.
        /// </summary>
        internal static string messageBoxText_FechaTutoriaConcluida {
            get {
                return ResourceManager.GetString("messageBoxText_FechaTutoriaConcluida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para llenar el reporte de tutoría antes debe registrar el horario de la sesión.
        /// </summary>
        internal static string messageBoxText_HorarioSinRegistrar {
            get {
                return ResourceManager.GetString("messageBoxText_HorarioSinRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemática no seleccionada, Por favor seleccione alguna de la tabla e intentelo de nuevo..
        /// </summary>
        internal static string messageBoxText_ProblematicaNoSeleccionada {
            get {
                return ResourceManager.GetString("messageBoxText_ProblematicaNoSeleccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error de conexión al asignar los siguientes programas educativos al académico: .
        /// </summary>
        internal static string messageBoxText_ProgramasEducativosNoAsignados {
            get {
                return ResourceManager.GetString("messageBoxText_ProgramasEducativosNoAsignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione por lo menos un programa educativo..
        /// </summary>
        internal static string messageBoxText_ProgramasEducativosNoSeleccionados {
            get {
                return ResourceManager.GetString("messageBoxText_ProgramasEducativosNoSeleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información se registró correctamente en el sistema..
        /// </summary>
        internal static string messageBoxText_RegistroExitoso {
            get {
                return ResourceManager.GetString("messageBoxText_RegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya ha entregado el reporte para la fecha actual de tutoria.
        /// </summary>
        internal static string messageBoxText_ReporteEntregado {
            get {
                return ResourceManager.GetString("messageBoxText_ReporteEntregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese por lo menos un comentario general o una problemática académica..
        /// </summary>
        internal static string messageBoxText_ReporteTutoriaVacio {
            get {
                return ResourceManager.GetString("messageBoxText_ReporteTutoriaVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin cambios detectados.
        /// </summary>
        internal static string messageBoxText_SinCambios {
            get {
                return ResourceManager.GetString("messageBoxText_SinCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ningún tutor ha registrado su reporte de tutoría académica para esta fecha de tutoría..
        /// </summary>
        internal static string messageBoxText_SinReportesRegistrados {
            get {
                return ResourceManager.GetString("messageBoxText_SinReportesRegistrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Académico existente.
        /// </summary>
        internal static string messageBoxTitle_AcademicoExistente {
            get {
                return ResourceManager.GetString("messageBoxTitle_AcademicoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Académico no seleccionado..
        /// </summary>
        internal static string messageBoxTitle_AcademicoNoSeleccionado {
            get {
                return ResourceManager.GetString("messageBoxTitle_AcademicoNoSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Académicos no encontrados..
        /// </summary>
        internal static string messageBoxTitle_AcademicosNoEncontrados {
            get {
                return ResourceManager.GetString("messageBoxTitle_AcademicosNoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos vacíos.
        /// </summary>
        internal static string messageBoxTitle_CamposVacios {
            get {
                return ResourceManager.GetString("messageBoxTitle_CamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar operación.
        /// </summary>
        internal static string messageBoxTitle_CancelarOperacion {
            get {
                return ResourceManager.GetString("messageBoxTitle_CancelarOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pérdida de conexión.
        /// </summary>
        internal static string messageBoxTitle_Conexion {
            get {
                return ResourceManager.GetString("messageBoxTitle_Conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pérdida de conexión a internet.
        /// </summary>
        internal static string messageBoxTitle_ConexionInternet {
            get {
                return ResourceManager.GetString("messageBoxTitle_ConexionInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación.
        /// </summary>
        internal static string messageBoxTitle_ConfirmacionCambios {
            get {
                return ResourceManager.GetString("messageBoxTitle_ConfirmacionCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudiante existente.
        /// </summary>
        internal static string messageBoxTitle_EstudianteExistente {
            get {
                return ResourceManager.GetString("messageBoxTitle_EstudianteExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de tutoría termino.
        /// </summary>
        internal static string messageBoxTitle_FechaTutoriaConcluida {
            get {
                return ResourceManager.GetString("messageBoxTitle_FechaTutoriaConcluida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario no registrado.
        /// </summary>
        internal static string messageBoxTitle_HorarioSinRegistrar {
            get {
                return ResourceManager.GetString("messageBoxTitle_HorarioSinRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Límite de campos.
        /// </summary>
        internal static string messageBoxTitle_LimiteDeCampos {
            get {
                return ResourceManager.GetString("messageBoxTitle_LimiteDeCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemática no seleccionada.
        /// </summary>
        internal static string messageBoxTitle_ProblematicaNoSeleccionada {
            get {
                return ResourceManager.GetString("messageBoxTitle_ProblematicaNoSeleccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programa educativo no seleccionado.
        /// </summary>
        internal static string messageBoxTitle_ProgramasEducativosNoSeleccionados {
            get {
                return ResourceManager.GetString("messageBoxTitle_ProgramasEducativosNoSeleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte entregado.
        /// </summary>
        internal static string messageBoxTitle_ReporteEntregado {
            get {
                return ResourceManager.GetString("messageBoxTitle_ReporteEntregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de tutoría vacío.
        /// </summary>
        internal static string messageBoxTitle_ReporteTutoriaVacio {
            get {
                return ResourceManager.GetString("messageBoxTitle_ReporteTutoriaVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe modificar por lo menos un campo..
        /// </summary>
        internal static string messageBoxTitle_SinCambios {
            get {
                return ResourceManager.GetString("messageBoxTitle_SinCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin reportes registrados..
        /// </summary>
        internal static string messageBoxTitle_SinReportesRegistrados {
            get {
                return ResourceManager.GetString("messageBoxTitle_SinReportesRegistrados", resourceCulture);
            }
        }
    }
}
