//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudiantes()
        {
            this.Horarios = new HashSet<Horarios>();
            this.Problematicas = new HashSet<Problematicas>();
            this.ExperienciasEducativas_Academicos = new HashSet<ExperienciasEducativas_Academicos>();
        }
    
        public string Matricula { get; set; }
        public string Nombre { get; set; }
        public string ApellidoMaterno { get; set; }
        public string ApellidoPaterno { get; set; }
        public int SemestreQueCursa { get; set; }
        public bool EnRiesgo { get; set; }
        public string CorreoPersonal { get; set; }
        public string CorreoInstitucional { get; set; }
        public int IdProgramaEducativo { get; set; }
        public Nullable<int> IdAcademico { get; set; }
    
        public virtual Academicos Academicos { get; set; }
        public virtual ProgramasEducativos ProgramasEducativos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horarios> Horarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Problematicas> Problematicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperienciasEducativas_Academicos> ExperienciasEducativas_Academicos { get; set; }
    }
}
