//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciasEducativas_Academicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExperienciasEducativas_Academicos()
        {
            this.Problematicas = new HashSet<Problematicas>();
            this.Estudiantes = new HashSet<Estudiantes>();
        }
    
        public int NRC { get; set; }
        public int IdProgramaEducativo { get; set; }
        public int IdExperienciaEducativa { get; set; }
        public Nullable<int> IdAcademico { get; set; }
    
        public virtual Academicos Academicos { get; set; }
        public virtual ExperienciasEducativas ExperienciasEducativas { get; set; }
        public virtual ProgramasEducativos ProgramasEducativos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Problematicas> Problematicas { get; set; }
        public virtual PeriodosEscolares PeriodosEscolares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudiantes> Estudiantes { get; set; }
    }
}
