//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FechasTutorias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FechasTutorias()
        {
            this.TutoriasAcademicas = new HashSet<TutoriasAcademicas>();
        }
    
        public int IdFechaTutoria { get; set; }
        public System.DateTime FechaTutoria { get; set; }
        public System.DateTime FechaCierreDeReporte { get; set; }
        public int NumeroSesion { get; set; }
        public int IdPeriodo { get; set; }
        public int IdProgramaEducativo { get; set; }
    
        public virtual PeriodosEscolares PeriodosEscolares { get; set; }
        public virtual ProgramasEducativos ProgramasEducativos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutoriasAcademicas> TutoriasAcademicas { get; set; }
    }
}
