//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public int IdHorarios { get; set; }
        public bool Asistencia { get; set; }
        public bool Riesgo { get; set; }
        public System.TimeSpan HoraTutoria { get; set; }
        public int IdTutoriaAcademica { get; set; }
        public string Matricula { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual TutoriasAcademicas TutoriasAcademicas { get; set; }
    }
}
