//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problematicas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Problematicas()
        {
            this.Soluciones = new HashSet<Soluciones>();
        }
    
        public int IdProblematica { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public int IdTutoriaAcademica { get; set; }
        public int NRC { get; set; }
        public string Matricula { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual ExperienciasEducativas_Academicos ExperienciasEducativas_Academicos { get; set; }
        public virtual TutoriasAcademicas TutoriasAcademicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soluciones> Soluciones { get; set; }
    }
}
