//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutoriasAcademicas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TutoriasAcademicas()
        {
            this.Horarios = new HashSet<Horarios>();
            this.Problematicas = new HashSet<Problematicas>();
        }
    
        public int IdTutoriaAcademica { get; set; }
        public string ComentarioGeneral { get; set; }
        public bool ReporteEntregado { get; set; }
        public int IdAcademico { get; set; }
        public int IdFechaTuria { get; set; }
    
        public virtual Academicos Academicos { get; set; }
        public virtual FechasTutorias FechasTutorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horarios> Horarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Problematicas> Problematicas { get; set; }
    }
}
